# -*- coding: utf-8 -*-
"""assignment-deeplearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djQxtN-0tZRXs45npettKaGq5gJThSv_
"""

pip install transformers==4.41.2

pip install streamlit

from transformers import pipeline
import streamlit as st
from PIL import Image

#function 1 : image to text'
pipe_image2text = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")

#input the picture
def image2txt(image):
    image = Image.open(image)
    keyword = pipe_image2text(image)[0]['generated_text']
    return keyword

#function 2 : text to a story'
def txt2story(text):
    pipe = pipeline("text-generation", model="pranavpsv/genre-story-generator-v2")
    story_txt = pipe(keyword)[0]['generated_text']
    return story_txt

#function 3 : text to audio'
def text2audio(story_text):
    pipe = pipeline("text-to-audio", model="Matthijs/mms-tts-eng")
    audio_data = pipe(story_text)
    return audio_data

def main():
  st.set_page_config(page_title="Your Image to Audio Story", page_icon="😊")
  st.header("Turn Your Image to Audio Story")
  uploaded_file = st.file_uploader("Select an Image...")

  if uploaded_file is not None:
    print(uploaded_file)
    bytes_data = uploaded_file.getvalue()
    with open(uploaded_file.name, "wb") as file:
        file.write(bytes_data)
    st.image(uploaded_file, caption="Uploaded Image", use_column_width=True)


    #Stage 1: image to text
    st.text('Processing image2txt...')
    scenario = image2txt(uploaded_file.name)
    st.write(scenario)

    #Stage 2: text to story
    st.text('Generating a story...')
    story = txt2story(scenario)
    st.write(story)

    #Stage 3: story to audio
    st.text('Generating audio data...')
    audio_data =txt2audio(story)

    # Play button
    if st.button("Play Audio"):
      # Get the audio array and sample rate
      audio_array = audio_data["audio"]
      sample_rate = audio_data["sampling_rate"]

      # Play audio directly using Streamlit
      st.audio(audio_array,
        sample_rate=sample_rate)

if __name__ == "__main__":
    main()